Made many bug fixes and improvements to the new Shock OS Imager. 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager-remove-cached-images 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager-write-image

diff --git a/shock-os-core-10-all/usr/bin/shock-os-imager b/shock-os-core-10-all/usr/bin/shock-os-imager
--- a/shock-os-core-10-all/usr/bin/shock-os-imager
+++ b/shock-os-core-10-all/usr/bin/shock-os-imager
@@ -163,7 +163,7 @@ do
 
     fi
 
-    output="$(yad --width=500 --height=280 --window-icon=shock-os-imager --title="Shock OS Imager" --form \
+    output="$(yad --width=500 --height=295 --window-icon=shock-os-imager --title="Shock OS Imager" --form \
                 --always-print-result \
                 --field="Version:":LBL '' \
                 --field="":CB "$versions_yad_cb" \
@@ -184,23 +184,37 @@ do
 
     arch="$(echo "$output" | awk -F'|' '{print $6}')"
 
+    arch="${arch//-/_}"
+
     device="$(echo "$output" | awk -F'|' '{print $8}')"
 
     device="${device%% *}"
 
+    imagevar="${version}_${edition}_${arch}"
+
     if [[ "$ex" == "0" ]] #Flash
     then
 
-        device_size="$(cat /sys/class/block/$(basename "$block_device")/size)"
+        device_size="$(cat /sys/class/block/$(basename "$device")/size)"
 
         free_space="$(df -B 1G / | awk 'NR==2 {print $4}')"
 
-        if (($((device_size * 512)) < 12884901888)) #if device is less than 12GB. Using 12GB because it is clearly bigger than 8GB but will allow any 16GB drive.
+        if [[ "$device" == "(null)" ]]
+        then
+
+            yad --width=600 --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: No device was selected. Please insert an SD card or USB drive that is at least 16 GBs in space to install Shock OS on." --button="Dismiss"\!gtk-close
+
+        elif ! lsblk "$device" &>/dev/null #if device is no longer connected
+        then
+
+            yad --width=600 --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: The device $device does not seem to be plugged in anymore. Please insert an SD card or USB drive that is at least 16 GBs in space to install Shock OS on." --button="Dismiss"\!gtk-close
+
+        elif (($((device_size * 512)) < 12884901888)) #if device is less than 12GB. Using 12GB because it is clearly bigger than 8GB but will allow any 16GB drive.
         then
 
             yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: The selected device is too small. The target device must be at least 16 GBs in size for Shock OS to work properly. Please try again with a larger SD card or USB drive." --button="Dismiss"\!gtk-close
 
-        elif ((free_space<5)) && [[ ! -f /usr/share/shock-os-imager/cache/images/"${version}_${edition}_${arch}.img.xz" ]] #if less than 5GB of free space on system and image isn't cached
+        elif ((free_space<5)) && [[ ! -f /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" ]] #if less than 5GB of free space on system and image isn't cached
         then
 
             if (($(ls /usr/share/shock-os-imager/cache/images | wc -l)!=0)) #if cached images
@@ -225,7 +239,7 @@ do
 
                 image_writer_output_dir="$(mktemp -d)"
 
-                { script -afe "$image_writer_output_dir"/output.txt -c "pkexec shock-os-imager-write-image \"$version\" \"$edition\" \"$arch\" \"$device\" \"$image_writer_output_dir\"" || touch "$image_writer_output_dir"/cancelled_indicator; echo "$?" | tee "$image_writer_output_dir"/image_writer_ex; } & image_writer_pid=$!
+                script -afe "$image_writer_output_dir"/output.txt -c "pkexec bash -c '/usr/bin/shock-os-imager-write-image \"$version\" \"$edition\" \"$arch\" \"$device\" \"$image_writer_output_dir\"; echo \"\$?\" | tee \"$image_writer_output_dir\"/image_writer_ex'" || touch "$image_writer_output_dir"/cancelled_indicator & image_writer_pid=$!
 
                 { inotifywait -m -e create "$image_writer_output_dir" & echo $! | tee "$image_writer_output_dir"/inotifywait_pid; } | while read -r event #wait for pkexec password to be entered
                 do
@@ -281,10 +295,12 @@ do
 
                     echo "IMAGE_WRITER_EX: $image_writer_ex" #DEBUG
 
-                    if [[ "$image_writer_ex" == "0" ]]
+                    if [[ "$image_writer_ex" == "0" ]] #sends out success/fail notification
                     then
 
                         notify-send --app-name="Shock OS Imager" --icon=shock-os-imager "Device Flashed Successfully!" "The device ($device) was successfully flashed. Feel free to remove it."
+
+                        yad --window-icon=shock-os-imager --image=emblem-default-symbolic --title="Shock OS Imager" --text="The device ($device) was successfully flashed. Feel free to remove it." --button="Dismiss"\!gtk-close
 
                     else
 
@@ -292,11 +308,53 @@ do
 
                     fi
 
+                    if [[ "$image_writer_ex" == "2" ]] #If failed to achieve root
+                    then
+
+                        yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: Failed to achieve root access." --button="Dismiss"\!gtk-close
+
+                    elif [[ "$image_writer_ex" == "3" ]] #If failed to download something
+                    then
+
+                        yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: Failed to download the required files. Please check your internet connection and try again later." --button="Dismiss"\!gtk-close
+
+                    elif [[ "$image_writer_ex" == "4" ]] #If image was corruped
+                    then
+
+                        if [[ -f /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" ]]
+                        then
+
+                            yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: The image has been corrupted. Would you like to delete it?" --button="Yes, remove"\!gtk-ok --button="No, keep"\!gtk-cancel
+
+                            ex=$?
+
+                            if [[ "$ex" == "0" ]]
+                            then
+
+                                pkexec rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"
+
+                            fi
+
+                        else
+
+                            yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: The image has been corrupted." --button="Dismiss"\!gtk-close
+
+                        fi
+
+                    elif [[ "$image_writer_ex" == "5" ]] #If flashing error occured
+                    then
+
+                        yad --window-icon=shock-os-imager --image=emblem-important-symbolic --title="Shock OS Imager" --text="ERROR: An error occured while flashing the device." --button="Dismiss"\!gtk-close
+
+                    fi  
+
                 else
 
                     yad --window-icon=shock-os-imager --image=emblem-default-symbolic --title="Shock OS Imager" --text="Operation aborted. No changes were made to device ${device}." --button="Dismiss"\!gtk-close
 
                 fi
+
+                rm -rf "$image_writer_output_dir"
 
             else
 
diff --git a/shock-os-core-10-all/usr/bin/shock-os-imager-write-image b/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
--- a/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
+++ b/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
@@ -7,7 +7,7 @@ then
 
     echo "Script must be run as root. Exiting..."
 
-    exit
+    exit 2
 
 fi
 
@@ -19,11 +19,11 @@ edition="$2"
 
 arch="$3"
 
-arch="${arch//-/_}"
-
 device="$4"
 
 image_writer_output_dir="$5"
+
+imagevar="${version}_${edition}_${arch}"
 
 if [[ ! -f /usr/share/shock-os-imager/settings.ini ]]
 then
@@ -37,7 +37,7 @@ source /usr/share/shock-os-imager/settings.ini
 
 touch "$image_writer_output_dir"/ready_indicator
 
-{ inotifywait -m "$image_writer_output_dir" & inotifywait_killpid=$!; } | while read -r event
+{ inotifywait -m "$image_writer_output_dir" & echo "$!" | tee "$image_writer_output_dir"/inotifywait_killpid; } | while read -r event
 do
 
     if [[ -f "${image_writer_output_dir}/kill_indicator" ]]
@@ -45,12 +45,21 @@ do
 
         echo "CANCELLING..."
 
-        kill $$
+        if [[ -f "${image_writer_output_dir}/image_download_pid" ]]
+        then
+
+            kill -9 "$(cat "$image_writer_output_dir"/image_download_pid)"
+
+        else
+
+            kill $$
+
+        fi
 
     elif [[ ! -f "${image_writer_output_dir}/output.txt" ]]
     then
 
-        kill "$inotifywait_killpid"
+        kill "$(cat "$image_writer_output_dir"/inotifywait_killpid)"
 
     fi
 
@@ -64,22 +73,43 @@ rm /usr/share/shock-os-imager/metainfo
 
 rm -rf /usr/share/shock-os-imager/cache/sigs/*
 
+sleep 1
+
 echo "#Getting metadata..."
 
-wget -q https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/metainfo -P /usr/share/shock-os-imager/
+sleep 1
+
+wget --timeout=5 -q https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/metainfo -P /usr/share/shock-os-imager/ || { echo 'ERROR: FAILED TO DOWNLOAD METAINFO'; exit 3; }
 
 source /usr/share/shock-os-imager/metainfo
 
-imagevar="${version}_${edition}_${arch}"
-
 if [[ ! -f /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" ]]
 then
+
+    sleep 1
+
+    echo "#Downloading image..."
+
+    sleep 1
 
     url="${imagevar}_url"
 
     url="${!url}"
 
-    wget -O --connect-timeout=20 /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" "$url" 2>&1 || rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/'
+    { { wget --timeout=20 -O /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" "$url" 2>&1 || { rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"; echo 'ERROR: FAILED TO DOWNLOAD IMAGE'; exit 3; }; } | sed -n 's/.* \([0-9]\{1,2\}\)%.*/\1/p'; } & echo "$!" | tee "$image_writer_output_dir"/image_download_pid
+
+    sleep 1
+
+    wait "$(cat "$image_writer_output_dir"/image_download_pid)"
+
+    if [[ -f "${image_writer_output_dir}/kill_indicator" ]] #YES, this IS needed (mostly for if the process was cancelled during the download)
+    then
+
+        rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"
+
+        exit 1
+
+    fi
 
 fi
 
@@ -87,19 +117,11 @@ sig_url="${imagevar}_sig_url"
 
 sig_url="${!sig_url}"
 
-echo "#Getting signature..."
-
-wget -q -O /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" "$sig_url"
+sleep 1
 
 echo "#Verifying image..."
 
-rm /usr/share/shock-os-imager/key.asc
-
-wget https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/key.asc -P /usr/share/shock-os-imager/
-
-gpg --import /usr/share/shock-os-imager/key.asc
-
-gpg --verify /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" || { echo 'ERROR: IMAGE FILE DID NOT MATCH SIGNATURE!!!'; exit 1; }
+sleep 1
 
 imagevar_compressed_sha256sum="${imagevar}_compressed_sha256sum"
 
@@ -108,13 +130,33 @@ compressed_sha256sum="$(pv -n /usr/share/shock-os-imager/cache/images/"${imageva
 if [[ "$compressed_sha256sum" != "${!imagevar_compressed_sha256sum}" ]]
 then
 
-    echo 'ERROR: INVALID sha256SUM, FILE HAS BEEN TAMPERED WITH!!!'
+    echo 'ERROR: INVALID SHA256SUM, IMAGE IS CORRUPTED.'
 
-    exit 1
+    exit 4
 
 fi
 
+sleep 1
+
+echo "#Getting signature..."
+
+sleep 1
+
+wget --timeout=5 -q -O /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" "$sig_url" || { echo 'ERROR: FAILED TO DOWNLOAD SIGNATURE'; exit 3; }
+
+rm /usr/share/shock-os-imager/key.asc
+
+wget --timeout=5 https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/key.asc -P /usr/share/shock-os-imager/ || { echo 'ERROR: FAILED TO DOWNLOAD KEY'; exit 3; }
+
+gpg --import /usr/share/shock-os-imager/key.asc
+
+gpg --verify /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" || { echo 'ERROR: IMAGE FILE DID NOT MATCH SIGNATURE.'; exit 4; }
+
+sleep 1
+
 echo "#Writing image..."
+
+sleep 1
 
 umount $device*
 
@@ -128,7 +170,11 @@ dd_output="$(xz -cd /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"
 
 echo "DD_OUTPUT: $dd_output" #DEBUG
 
+sleep 1
+
 echo "#Verifying device..."
+
+sleep 1
 
 uncompressed_size="$(echo "$dd_output" | awk 'NR==3 {print $1}')"
 
@@ -139,9 +185,9 @@ imagevar_uncompressed_sha256sum="${imagevar}_uncompressed_sha256sum"
 if [[ "$device_sha256sum" != "${!imagevar_uncompressed_sha256sum}" ]]
 then
 
-    echo 'ERROR: VERIFICATION FAILED, AN ERROR OCCURRED WHILE FLASHING!!!'
+    echo 'ERROR: VERIFICATION FAILED, AN ERROR OCCURRED WHILE FLASHING.'
 
-    exit 1
+    exit 5
 
 fi
 
