Prepended `GDK_BACKEND=x11` to many YAD commands. The tabbed windows now work under Wayland, and the window icons now show. Hopefully this won't be a permanent thing as YAD will eventually be ported (or forked) over to Wayland. 	modified:   shock-os-core-10-all/usr/bin/shock-fonts 	modified:   shock-os-core-10-all/usr/bin/shock-initial-setup 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager-remove-cached-images 	modified:   shock-os-core-10-all/usr/bin/shock-os-imager-write-image 	modified:   shock-os-core-10-all/usr/bin/shock-package-installer 	modified:   shock-os-core-10-all/usr/bin/shock-parental-controls 	modified:   shock-os-core-10-all/usr/bin/shock-pulseaudio-autoconfig 	modified:   shock-os-core-10-all/usr/bin/shock-release-scanner 	modified:   shock-os-core-10-all/usr/bin/shock-release-upgrader 	modified:   shock-os-core-10-all/usr/bin/shock-screentime 	modified:   shock-os-core-10-all/usr/bin/shock-screentime-timeleft 	modified:   shock-os-core-10-all/usr/bin/shock-startup-sound-chooser 	modified:   shock-os-core-10-all/usr/bin/shock-themes 	modified:   shock-os-core-10-all/usr/bin/shock-update-manager 	modified:   shock-os-core-10-all/usr/bin/shock-updates-scanner 	modified:   shock-os-core-10-all/usr/bin/shock-webapp-launcher 	modified:   shock-os-core-10-all/usr/bin/shock-webapps 	modified:   shock-os-core-10-all/usr/bin/shockver 	modified:   shock-os-core-10-all/usr/bin/shockware-center 	modified:   shock-os-core-10-all/usr/bin/shockware-center-view-package 	modified:   shock-os-core-10-all/usr/share/shock/dist-info 	modified:   shock-os-gnome-desktop-10-all/usr/bin/shock-gnome-layouts 	modified:   shock-os-gnome-desktop-10-all/usr/bin/shock-welcome

diff --git a/shock-os-core-10-all/usr/bin/shock-os-imager-write-image b/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
--- a/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
+++ b/shock-os-core-10-all/usr/bin/shock-os-imager-write-image
@@ -35,22 +35,22 @@ fi
 
 source /usr/share/shock-os-imager/settings.ini
 
-touch "$tmpdir"/writer/ready_indicator
+touch "$tmpdir"/ready_indicator
 
-{ inotifywait -m -e create,delete "$tmpdir"/writer & echo "$!" | tee "$tmpdir"/writer/inotifywait_killpid; } | while read -r event
+{ inotifywait -m -e create,delete "$tmpdir" & echo "$!" | tee "$tmpdir"/inotifywait_killpid; } | while read -r event
 do
 
-    if [[ -f "${tmpdir}/writer/kill_indicator" ]]
+    if [[ -f "${tmpdir}/kill_indicator" ]]
     then
 
-        kill "$(cat "$tmpdir"/writer/inotifywait_killpid)"
+        kill "$(cat "$tmpdir"/inotifywait_killpid)"
 
         echo "CANCELLING..."
 
-        if [[ -f "${tmpdir}/writer/image_download_pid" ]]
+        if [[ -f "${tmpdir}/image_download_pid" ]]
         then
 
-            kill -9 "$(cat "$tmpdir"/writer/image_download_pid)"
+            kill -9 "$(cat "$tmpdir"/image_download_pid)"
 
         else
 
@@ -58,22 +58,16 @@ do
 
         fi
 
-    elif [[ ! -f "${tmpdir}/writer/output.txt" ]]
+    elif [[ ! -f "${tmpdir}/output.txt" ]]
     then
 
-        kill "$(cat "$tmpdir"/writer/inotifywait_killpid)"
+        kill "$(cat "$tmpdir"/inotifywait_killpid)"
 
     fi
 
 done &
 
-mkdir -p /usr/share/shock-os-imager/cache/images
-
-mkdir -p /usr/share/shock-os-imager/cache/sigs
-
-rm /usr/share/shock-os-imager/metadata
-
-rm -rf /usr/share/shock-os-imager/cache/sigs/*
+mkdir -p /usr/share/shock-os-imager/cached-images
 
 sleep 1
 
@@ -81,16 +75,16 @@ echo "#Getting metadata..."
 
 sleep 1
 
-wget --retry-connrefused --tries=0 --timeout=5 -q https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/metadata -P /usr/share/shock-os-imager/ || { echo 'ERROR: FAILED TO DOWNLOAD METADATA'; exit 3; }
+gpg --import "$tmpdir"/key.asc
 
-wget --retry-connrefused --tries=0 --timeout 5 https://github.com/Shock-OS/Shock-OS/raw/imager/metadata.sig -P /usr/share/shock-os-imager/
+gpg --verify "$tmpdir"/metadata.sig "$tmpdir"/metadata || { echo "ERROR: FAILED TO VERIFY METADATA"; exit 4; }
 
-gpg --verify /usr/share/shock-os-imager/metadata.sig /usr/share/shock-os-imager/metadata || { echo "ERROR: FAILED TO VERIFY METADATA"; exit 4; }
+source "$tmpdir"/metadata
 
-source /usr/share/shock-os-imager/metadata
-
-if [[ ! -f /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" ]]
+if [[ ! -f /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" ]]
 then
+
+    echo "0"
 
     sleep 1
 
@@ -102,20 +96,20 @@ then
 
     url="${!url}"
 
-    { { wget --retry-connrefused --tries=0 --timeout=20 -O /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" "$url" 2>&1 || rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"; } | sed -u 's/.* \([0-9]\+\)% .*/\1\n#Downloading image... (\1%)/'; } & echo "$!" | tee "$tmpdir"/writer/image_download_pid
+    { { wget --retry-connrefused --tries=0 --timeout=20 -O /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" "$url" 2>&1 || rm -rf /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz"; } | sed -u 's/.* \([0-9]\+\)% .*/\1\n#Downloading image... (\1%)/'; } & echo "$!" | tee "$tmpdir"/image_download_pid
 
     sleep 1
 
-    wait "$(cat "$tmpdir"/writer/image_download_pid)"
+    wait "$(cat "$tmpdir"/image_download_pid)"
 
-    if [[ -f "${tmpdir}/writer/kill_indicator" ]] #YES, this IS needed (mostly for if the process was cancelled during the download)
+    if [[ -f "${tmpdir}/kill_indicator" ]] #YES, this IS needed (mostly for if the process was cancelled during the download)
     then
 
-        rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"
+        rm -rf /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz"
 
         exit 1
 
-    elif [[ ! -f /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" ]] #if file deleted because download failed
+    elif [[ ! -f /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" ]] #if file deleted because download failed
     then
 
         echo "ERROR: FAILED TO DOWNLOAD IMAGE"
@@ -138,7 +132,7 @@ sleep 1
 
 imagevar_compressed_sha256sum="${imagevar}_compressed_sha256sum"
 
-compressed_sha256sum="$(pv -n /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" | sha256sum | cut -d' ' -f1)"
+compressed_sha256sum="$(pv -n /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" | sha256sum | cut -d' ' -f1)"
 
 if [[ "$compressed_sha256sum" != "${!imagevar_compressed_sha256sum}" ]]
 then
@@ -155,15 +149,9 @@ echo "#Getting signature..."
 
 sleep 1
 
-wget --retry-connrefused --tries=0 --timeout=5 -q -O /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" "$sig_url" || { echo 'ERROR: FAILED TO DOWNLOAD SIGNATURE'; exit 3; }
+wget --retry-connrefused --tries=0 --timeout=5 -q -O "$tmpdir"/"${imagevar}.img.xz.sig" "$sig_url" || { echo 'ERROR: FAILED TO DOWNLOAD SIGNATURE'; exit 3; }
 
-rm /usr/share/shock-os-imager/key.asc
-
-wget --retry-connrefused --tries=0 --timeout=5 https://raw.githubusercontent.com/Shock-OS/Shock-OS/imager/key.asc -P /usr/share/shock-os-imager/ || { echo 'ERROR: FAILED TO DOWNLOAD KEY'; exit 3; }
-
-gpg --import /usr/share/shock-os-imager/key.asc
-
-gpg --verify /usr/share/shock-os-imager/cache/sigs/"${imagevar}.img.xz.sig" /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" || { echo 'ERROR: IMAGE FILE DID NOT MATCH SIGNATURE.'; exit 5; }
+gpg --verify "$tmpdir"/"${imagevar}.img.xz.sig" /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" || { echo 'ERROR: IMAGE FILE DID NOT MATCH SIGNATURE.'; exit 5; }
 
 sleep 1
 
@@ -173,13 +161,13 @@ sleep 1
 
 umount $device*
 
-image_size=$(xz -l /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" | awk 'NR==2 {print $5}')
+image_size=$(xz -l /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" | awk 'NR==2 {print $5}')
 
 image_size=$(echo "$image_size" | sed 's/,//g' | cut -d '.' -f 1)
 
 image_size=$((image_size*1024*1024))
 
-dd_output="$(xz -cd /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz" | pv -s "$image_size" -n | dd of=$device bs=4M 2>&1)"
+dd_output="$(xz -cd /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz" | pv -s "$image_size" -n | dd of=$device bs=4M 2>&1)"
 
 echo "DD_OUTPUT: $dd_output" #DEBUG
 
@@ -207,7 +195,7 @@ fi
 if [[ "$caching_enabled" == "FALSE" ]]
 then
 
-    rm -rf /usr/share/shock-os-imager/cache/images/"${imagevar}.img.xz"
+    rm -rf /usr/share/shock-os-imager/cached-images/"${imagevar}.img.xz"
 
 fi
 
