Finished porting the icons for the Shock OS homegrown apps to the Yaru icon theme. Some directories have been updated, and stuff that is needed during the installation of Shock OS, but is obsolete after (typically located in `/usr/share/shock`) is now in `/usr/share/shock/install-temp`, and is removed once it is no longer needed.

diff --git a/shock-os-core-9-all/usr/bin/shock-os-imager b/shock-os-core-9-all/usr/bin/shock-os-imager
--- a/shock-os-core-9-all/usr/bin/shock-os-imager
+++ b/shock-os-core-9-all/usr/bin/shock-os-imager
@@ -32,7 +32,7 @@ do
 		if [[ ! -f /usr/share/shock-os-imager/images ]]
 		then
 
-			yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --image=emblem-important --title="Shock OS Imager" --text="Shock OS Imager requires an internet connection. Please reconnect to the internet and hit 'Retry'." --button="Retry"\!edit-undo
+			yad --window-icon=shock-os-imager --image=emblem-important --title="Shock OS Imager" --text="Shock OS Imager requires an internet connection. Please reconnect to the internet and hit 'Retry'." --button="Retry"\!edit-undo
 
 			ex=$?
 
@@ -123,7 +123,7 @@ do
 
     fi
 
-	output="$(yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="Install Shock OS onto an external storage device." --form --field="SD card/USB drive:":CB "$drives_selection" --field="Shock OS version:":CB "$images" "$cached_images_button" --button="Refresh"\!gtk-refresh:10 --button="Flash"\!/usr/share/shock/shock-logo.svg:20)"
+	output="$(yad --window-icon=shock-os-imager --title="Shock OS Imager" --text="Install Shock OS onto an external storage device." --form --field="SD card/USB drive:":CB "$drives_selection" --field="Shock OS version:":CB "$images" "$cached_images_button" --button="Refresh"\!gtk-refresh:10 --button="Flash"\!/usr/share/shock/shock-logo.svg:20)"
 
 	ex=$?
 
@@ -147,7 +147,7 @@ do
 
         fi
 
-        yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="$rmci_text" --button="Yes, remove"\!gtk-ok --button="No, keep"\!gtk-cancel
+        yad --window-icon=shock-os-imager --title="Shock OS Imager" --text="$rmci_text" --button="Yes, remove"\!gtk-ok --button="No, keep"\!gtk-cancel
 
         ex=$?
 
@@ -156,26 +156,26 @@ do
 
             rm -rf /usr/share/shock-os-imager/cached-images/*
 
-            yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --image=emblem-default --title="Shock OS Imager" --text="All cached images have been successfully removed." --button="Dismiss"\!gtk-cancel
+            yad --window-icon=shock-os-imager --image=emblem-default --title="Shock OS Imager" --text="All cached images have been successfully removed." --button="Dismiss"\!gtk-cancel
 
         fi
 
 	elif [[ "$target_drive" == "(null)" ]] && ((ex==20))
 	then
 
-		zenity --window-icon=/usr/share/shock/icons/shock-os-imager.svg --error --title="Shock OS Imager" --text="You have not selected a drive to flash. Please plug in a storage device to install Shock OS on, and then click 'Retry'" --ok-label="Retry" --width=300
+		zenity --window-icon=shock-os-imager --error --title="Shock OS Imager" --text="You have not selected a drive to flash. Please plug in a storage device to install Shock OS on, and then click 'Retry'" --ok-label="Retry" --width=300
 
     elif [[ -z "$(lsblk -o PATH | grep -w $target_drive)" ]] && ((ex==20)) #if error reading the device (perhaps it was unplugged)
     then
 
-        zenity --window-icon=/usr/share/shock/icons/shock-os-imager.svg --error --title="Shock OS Imager" --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Retry" --width=300
+        zenity --window-icon=shock-os-imager --error --title="Shock OS Imager" --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Retry" --width=300
 
 	elif (($(lsblk -o PATH,SIZE -b | grep -w $target_drive | awk '{print $2}')<15000000000)) && ((ex==20)) #if drive is less than 16GB
     then
 
 		target_drive="(null)"
 
-        zenity --window-icon=/usr/share/shock/icons/shock-os-imager.svg --error --title="Shock OS Imager" --text="The SD card/USB drive you selected is too small. Shock OS requires a storage device of at least 16GB. Please insert a storage device that is at least 16GB in size, then press 'Retry' when you are ready to continue." --ok-label="Retry" --width=300
+        zenity --window-icon=shock-os-imager --error --title="Shock OS Imager" --text="The SD card/USB drive you selected is too small. Shock OS requires a storage device of at least 16GB. Please insert a storage device that is at least 16GB in size, then press 'Retry' when you are ready to continue." --ok-label="Retry" --width=300
 
     elif ((ex!=10)) && ((ex!=20))
 	then
@@ -236,7 +236,7 @@ then
 
             }
 
-        } | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --progress --width=300 --height=100 --center --fixed --auto-close --auto-kill --button="Cancel"\!gtk-cancel:1
+        } | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | yad --window-icon=shock-os-imager --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --progress --width=300 --height=100 --center --fixed --auto-close --auto-kill --button="Cancel"\!gtk-cancel:1
 
 		mv /usr/share/shock-os-imager/cached-images/download /usr/share/shock-os-imager/cached-images/$filename
 
@@ -247,22 +247,22 @@ then
     # Launch the command in the background and capture its PID
     {
 
-    mkdir -p /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Could Not Refresh Cache" --text="The directory /usr/share/shock-os-imager/sha256sums does not exist and could not be created." --ok-label="Exit"; exit 1; }
+    mkdir -p /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=shock-os-imager --title="Could Not Refresh Cache" --text="The directory /usr/share/shock-os-imager/sha256sums does not exist and could not be created." --ok-label="Exit"; exit 1; }
 
-    rm -rf /usr/share/shock-os-imager/sha256sums/* || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Could Not Refresh Cache" --text="Failed to remove files from /usr/share/shock-os-imager/sha256sums." --ok-label="Exit"; exit 1; }
+    rm -rf /usr/share/shock-os-imager/sha256sums/* || { zenity --error --window-icon=shock-os-imager --title="Could Not Refresh Cache" --text="Failed to remove files from /usr/share/shock-os-imager/sha256sums." --ok-label="Exit"; exit 1; }
 
-    wget https://raw.githubusercontent.com/Shock-OS/shock-os-imager/main/shockos.asc -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Failed to Verify Image" --text="Failed to download the GPG key to verify the image." --ok-label="Exit"; exit 1; }
+    wget https://raw.githubusercontent.com/Shock-OS/shock-os-imager/main/shockos.asc -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=shock-os-imager --title="Failed to Verify Image" --text="Failed to download the GPG key to verify the image." --ok-label="Exit"; exit 1; }
 
-    gpg --import /usr/share/shock-os-imager/sha256sums/shockos.asc || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Failed to Import Key" --text="Failed to import the GPG key to verify the image." --ok-label="Exit"; exit 1; }
+    gpg --import /usr/share/shock-os-imager/sha256sums/shockos.asc || { zenity --error --window-icon=shock-os-imager --title="Failed to Import Key" --text="Failed to import the GPG key to verify the image." --ok-label="Exit"; exit 1; }
 
-    wget https://raw.githubusercontent.com/Shock-OS/shock-os-imager/main/sha256sums -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Failed to Fetch sha256sums" --text="Failed to fetch the sha256sums to verify the image." --ok-label="Exit"; exit 1; }
+    wget https://raw.githubusercontent.com/Shock-OS/shock-os-imager/main/sha256sums -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=shock-os-imager --title="Failed to Fetch sha256sums" --text="Failed to fetch the sha256sums to verify the image." --ok-label="Exit"; exit 1; }
 
-    wget https://github.com/Shock-OS/shock-os-imager/raw/main/sha256sums.sig -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Failed to Fetch sha256sums.sig" --text="Failed to fetch the sha256sums.sig to verify the image." --ok-label="Exit"; exit 1; }
+    wget https://github.com/Shock-OS/shock-os-imager/raw/main/sha256sums.sig -P /usr/share/shock-os-imager/sha256sums || { zenity --error --window-icon=shock-os-imager --title="Failed to Fetch sha256sums.sig" --text="Failed to fetch the sha256sums.sig to verify the image." --ok-label="Exit"; exit 1; }
 
     if [[ "$(gpg --verify /usr/share/shock-os-imager/sha256sums/sha256sums.sig /usr/share/shock-os-imager/sha256sums/sha256sums 2>&1 | grep 'Primary key fingerprint:')" != "Primary key fingerprint: 9515 D970 4C1B 1B3B 58CB  606D D2EA 4E12 F633 2179" ]]
     then
 
-        zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Invalid sha256sums" --text="sha256sums has been tampered with during or after it was downloaded. Please double check your computer and your internet router for viruses and malware." --ok-label="Exit"
+        zenity --error --window-icon=shock-os-imager --title="Invalid sha256sums" --text="sha256sums has been tampered with during or after it was downloaded. Please double check your computer and your internet router for viruses and malware." --ok-label="Exit"
 
         exit 1
 
@@ -275,7 +275,7 @@ then
     if [[ "$(sha256sum -b /usr/share/shock-os-imager/cached-images/$filename | cut -d' ' -f1)" != "$sha256sum" ]]
     then
 
-        zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Invalid Image" --text="$filename was tampered with during or after it was downloaded. Please double check your computer and your internet router for viruses and malware." --ok-label="Exit"
+        zenity --error --window-icon=shock-os-imager --title="Invalid Image" --text="$filename was tampered with during or after it was downloaded. Please double check your computer and your internet router for viruses and malware." --ok-label="Exit"
 
         exit 1
 
@@ -285,7 +285,7 @@ then
 
     # Show the progress window using YAD
 
-    yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Verifying the Image" --text="Verifying $filename..." --progress --pulsate --progress-text="" --width=300 --height=100 --button="Cancel"\!gtk-cancel:1 & yad_pid=$!
+    yad --window-icon=shock-os-imager --title="Verifying the Image" --text="Verifying $filename..." --progress --pulsate --progress-text="" --width=300 --height=100 --button="Cancel"\!gtk-cancel:1 & yad_pid=$!
 
     # Wait for either the command to finish or the YAD window to close
     wait -n "$command_pid" "$yad_pid"
@@ -309,7 +309,7 @@ then
     if ((ex!=0))
     then
 
-        zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="The verification has been cancelled. The program will now exit." --ok-label="Exit"
+        zenity --error --window-icon=shock-os-imager --title="Shock OS Imager" --text="The verification has been cancelled. The program will now exit." --ok-label="Exit"
 
         kill $$
 
@@ -342,7 +342,7 @@ then
 
     # Show the progress window using YAD
 
-    yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --progress-text="" --width=300 --height=100 --center --fixed --button="Cancel"\!gtk-cancel:1 & yad_pid=$!
+    yad --window-icon=shock-os-imager --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --progress-text="" --width=300 --height=100 --center --fixed --button="Cancel"\!gtk-cancel:1 & yad_pid=$!
 
     # Wait for either the command to finish or the YAD window to close
     wait -n "$command_pid" "$yad_pid"
@@ -368,7 +368,7 @@ then
     if ((ex!=0))
     then
 
-        zenity --error --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="An error occurred when writing the image. The program will now exit." --ok-label="Exit"
+        zenity --error --window-icon=shock-os-imager --title="Shock OS Imager" --text="An error occurred when writing the image. The program will now exit." --ok-label="Exit"
 
         kill $$
 
@@ -376,9 +376,9 @@ then
 
 #THE WRITE SEGMENT ENDS
 
-	notify-send --app-name="Shock OS Imager" --icon=/usr/share/shock/icons/shock-os-imager.svg "Flashing Complete" "$image_to_flash_display has successfully been flashed to $target_drive_display_name."
+	notify-send --app-name="Shock OS Imager" --icon=shock-os-imager "Flashing Complete" "$image_to_flash_display has successfully been flashed to $target_drive_display_name."
 
-	yad --window-icon=/usr/share/shock/icons/shock-os-imager.svg --title="Shock OS Imager" --text="Congratulations! $image_to_flash_display has successfully been flashed to $target_drive_display_name. Thank you and enjoy!" --button="Dismiss"\!gtk-cancel
+	yad --window-icon=shock-os-imager --title="Shock OS Imager" --text="Congratulations! $image_to_flash_display has successfully been flashed to $target_drive_display_name. Thank you and enjoy!" --button="Dismiss"\!gtk-cancel
 
 elif ((ex!=10))
 then
