Shock OS Imager now supports SD cards. Bugs with parental controls have been fixed. 	modified:   shockos-9.0-all/usr/bin/shock-os-imager 	modified:   shockos-9.0-all/usr/bin/shock-parental-controls 	modified:   shockos-9.0-all/usr/bin/shock-users

diff --git a/shockos-9.0-all/usr/bin/shock-users b/shockos-9.0-all/usr/bin/shock-users
--- a/shockos-9.0-all/usr/bin/shock-users
+++ b/shockos-9.0-all/usr/bin/shock-users
@@ -221,7 +221,18 @@ then
         if [[ "$kidprofile" == "TRUE" ]]
         then
 
-            groupadd shock-child || (zenity --error --text="Failed to create the 'shock-child' group. The program will now exit." --ok-label="Exit" ; kill $$)
+            groupadd shock-child
+
+            ex=$?
+
+            if [[ "$ex" != "0" ]] && [[ "$ex" != "9" ]]
+            then
+
+                zenity --error --text="Failed to create the 'shock-child' group. The program will now exit." --ok-label="Exit"
+
+                exit 1
+
+            fi
 
             usermod -a -G adm,dialout,cdrom,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio,shock-child $x || (zenity --error --text="Failed to add the user to the required groups. The program will now exit." --ok-label="Exit" ; kill $$) #the user has been added to the required groups (excluding sudo)
 
