Automatic updates is now enabled/disabled from the settings menu in the Update Manager instead of its own app, along with a new option to enable/disable notification of new versions of Shock OS. The feature of being able to pause/resume automatic updates has been scrapped because it would just complicate things, and, realistically, when would that feature ever be useful? Various other changes and bug fixes have been committed. 	modified:   shockos-8.0-all/DEBIAN/control 	modified:   shockos-8.0-all/DEBIAN/postinst 	new file:   shockos-8.0-all/etc/xdg/autostart/shock-release-upgrader.desktop 	modified:   shockos-8.0-all/usr/bin/shock-auto-updates 	deleted:    shockos-8.0-all/usr/bin/shock-auto-updates-setup 	deleted:    shockos-8.0-all/usr/bin/shock-backup-and-restore 	modified:   shockos-8.0-all/usr/bin/shock-os-credits 	modified:   shockos-8.0-all/usr/bin/shock-os-imager 	modified:   shockos-8.0-all/usr/bin/shock-os-update-manager 	new file:   shockos-8.0-all/usr/bin/shock-package-installer 	modified:   shockos-8.0-all/usr/bin/shock-release-upgrader 	modified:   shockos-8.0-all/usr/bin/shock-welcome 	modified:   shockos-8.0-all/usr/bin/shockware-center 	modified:   shockos-8.0-all/usr/bin/shockware-center-view-package 	deleted:    shockos-8.0-all/usr/share/applications/automatic-updates.desktop 	deleted:    shockos-8.0-all/usr/share/applications/shock-backup-and-restore.desktop 	renamed:    shockos-8.0-all/usr/share/applications/Fonts.desktop -> shockos-8.0-all/usr/share/applications/shock-fonts.desktop 	new file:   shockos-8.0-all/usr/share/applications/shock-os-update-manager.desktop 	new file:   shockos-8.0-all/usr/share/applications/shock-package-installer.desktop 	renamed:    shockos-8.0-all/usr/share/applications/panel-layout-changer.desktop -> shockos-8.0-all/usr/share/applications/shock-panel-layout-changer.desktop 	renamed:    shockos-8.0-all/usr/share/applications/parental-controls.desktop -> shockos-8.0-all/usr/share/applications/shock-parental-controls.desktop 	renamed:    shockos-8.0-all/usr/share/applications/Desktop Background.desktop -> shockos-8.0-all/usr/share/applications/shock-wallpapers.desktop 	modified:   shockos-8.0-all/usr/share/applications/shockware-center.desktop 	modified:   shockos-8.0-all/usr/share/shock/credits 	deleted:    wip_apps/MOSTLY ACCURATE PACKAGE FETHCERS FOR SHOCKWARE CENTER/README 	deleted:    wip_apps/MOSTLY ACCURATE PACKAGE FETHCERS FOR SHOCKWARE CENTER/shockware-center-get-apt-names.py 	deleted:    wip_apps/MOSTLY ACCURATE PACKAGE FETHCERS FOR SHOCKWARE CENTER/shockware-center-get-apt-packages-names.py

diff --git a/shockos-8.0-all/usr/bin/shock-os-imager b/shockos-8.0-all/usr/bin/shock-os-imager
--- a/shockos-8.0-all/usr/bin/shock-os-imager
+++ b/shockos-8.0-all/usr/bin/shock-os-imager
@@ -21,9 +21,9 @@ rm /usr/share/shock-os-imager/images
 
 rm /usr/share/shock-os-imager/cached-images/download*
 
-target_drive="(null)"
+success2="FALSE"
 
-until [[ "$target_drive" != "(null)" ]] && [[ "$ex" == "20" ]]
+until [[ "$success2" == "TRUE" ]]
 do
 
 	internet="yes"
@@ -179,7 +179,18 @@ do
 
 	done
 
-	output="$(yad --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Install Shock OS onto an external storage device." --form --field="SD card/USB drive:":CB "$drives" --field="Shock OS version:":CB "$images" --button="Refresh"\!gtk-refresh:10 --button="Flash"\!start-here:20)"
+    if (($(ls /usr/share/shock-os-imager/cached-images | wc -l)>0))
+    then
+
+        cached_images_button='--button=Delete Cached Images!gtk-delete:30'
+
+    else
+
+        cached_images_button=""
+
+    fi
+
+	output="$(yad --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Install Shock OS onto an external storage device." --form --field="SD card/USB drive:":CB "$drives" --field="Shock OS version:":CB "$images" "$cached_images_button" --button="Refresh"\!gtk-refresh:10 --button="Flash"\!start-here:20)"
 
 	ex=$?
 
@@ -189,24 +200,63 @@ do
 
 	target_drive=$(echo "$target_drive" | cut -d' ' -f1)
 
-	if [[ "$target_drive" == "(null)" ]] && [[ "$ex" == "20" ]]
+    if [[ "$ex" == "30" ]] #delete cached images
+    then
+
+        if (($(ls /usr/share/shock-os-imager/cached-images | wc -l)>1)) #plural
+        then
+
+            rmci_text="There are $(ls /usr/share/shock-os-imager/cached-images | wc -l) cached images on your system, taking up a total of $(du -sh /usr/share/shock-os-imager/cached-images | awk '{print $1}') of space. Would you like to delete them?"
+
+        else #singular
+        
+            rmci_text="There is 1 cached image on your system, taking up a total of $(du -sh /usr/share/shock-os-imager/cached-images | awk '{print $1}') of space. Would you like to delete it?"
+
+        fi
+
+        yad --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="$rmci_text" --button="Yes, remove" --button="No, keep"
+
+        ex=$?
+
+        if [[ "$ex" == "0" ]]
+        then
+
+            rm -rf /usr/share/shock-os-imager/cached-images/*
+
+            yad --window-icon=/usr/share/shock-os-imager/icon.svg --image=emblem-default --title="Shock OS Imager" --text="All cached images have been successfully removed." --button="Dismiss"
+
+        fi
+
+	elif [[ "$target_drive" == "(null)" ]] && [[ "$ex" == "20" ]]
 	then
 
 		zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="You have not selected a drive to flash. Please plug in a storage device to install Shock OS on, and then click 'Retry'" --ok-label="Retry" --width=300
 
-	elif (($(sudo blockdev --getsize64 $target_drive)<15000000000)) && [[ "$ex" == "20" ]] #if drive is less than 16GB
+    elif [[ -z "$(lsblk -o PATH | grep -w $target_drive)" ]] && [[ "$ex" == "20" ]] #if error reading the device (perhaps it was unplugged)
+    then
+
+        zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Retry" --width=300
+
+	elif (($(lsblk -o PATH,SIZE -b | grep -w $target_drive | awk '{print $2}')<15000000000)) && [[ "$ex" == "20" ]] #if drive is less than 16GB
     then
 
 		target_drive="(null)"
 
-        zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="The SD card/USB Drive you selected is too small. Shock OS requires a storage device of at least 16GB. Please insert a storage device that is at least 16GB in size, then press 'Retry' when you are ready to continue." --ok-label="Retry" --width=300
+        zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="The SD card/USB drive you selected is too small. Shock OS requires a storage device of at least 16GB. Please insert a storage device that is at least 16GB in size, then press 'Retry' when you are ready to continue." --ok-label="Retry" --width=300
 
     elif [[ "$ex" != "10" ]] && [[ "$ex" != "20" ]]
 	then
 
 		exit
 
-	fi
+	elif [[ "$ex" == "20" ]]
+    then
+
+        success2="TRUE"
+
+    fi
+
+    echo "SUCCESS2: $success2" #DEBUG
 
 done
 
@@ -293,6 +343,15 @@ then
 		fi
 
 	fi
+
+    if [[ -z "$(lsblk -o PATH | grep -w $target_drive)" ]] #if error reading the device (perhaps it was unplugged)
+    then
+
+        zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Dismiss" --width=300
+
+        exit
+
+    fi
 
 	partitions=$(lsblk -n "$target_drive" | grep -c '^')
 
diff --git a/shockos-8.0-all/usr/bin/shock-os-update-manager b/shockos-8.0-all/usr/bin/shock-os-update-manager
--- a/shockos-8.0-all/usr/bin/shock-os-update-manager
+++ b/shockos-8.0-all/usr/bin/shock-os-update-manager
@@ -28,7 +28,7 @@ kill -9 $gui_killpid
 
 function install_updates() {
 
-pkexec apt upgrade -y
+pkexec env DEBIAN_FRONTEND=gnome apt upgrade -y
 
 ex=$?
 
@@ -76,10 +76,23 @@ all_updates=($(printf "%s\n" "${all_updates[@]}" | sort))
 
 }
 
-if [[ "$1" == "gui" ]] #if launched in GUI mode
+if [[ "$1" == "gui" ]] #if launched from the Shockware Center
 then
 
+    touch ~/.cache/shockware-center-launched-update-manager
+
+    eval "$(cat ~/.cache/shock-os-update-manager-notifications)"
+
+    (sleep 10 && rm ~/.cache/shockware-center-launched-update-manager) &
+
     start_loading_gui
+
+elif [[ -f /etc/sudoers.d/shock_automatic_updates ]]
+then
+
+    shock-auto-updates-kickstart
+
+    exit
 
 fi
 
@@ -90,7 +103,7 @@ then
 
 	echo "Your system is up to date."
 
-    if [[ "$1" == "gui" ]] #if launched in GUI mode
+    if [[ "$1" == "gui" ]] #if launched from the Shockware Center
     then
 
         end_loading
@@ -112,178 +125,256 @@ else
 
 fi
 
-if [[ "$1" != "gui" ]] #if NOT launched in GUI mode
-then
-
-    yad --notification --image=system-software-update --text="$text" --icon-size=48
-
-fi
-
-page=0
-
 while true
 do
 
-	start_loading
+    if [[ "$1" != "gui" ]] #if NOT launched from the Shockware Center
+    then
 
-	all_updates_show=("${all_updates[@]:$((rows_per_page*page))}")
+        yad --notification --image=system-software-update --text="$text" --icon-size=48 & notification_killpid=$!
 
-	all_updates_show=("${all_updates_show[@]::$((rows_per_page))}")
+        echo "kill -9 $notification_killpid" | tee -a ~/.cache/shock-os-update-manager-notifications
 
-	mapfile -t all_updates < <(printf '%s\n' "${all_updates[@]}" | sed 's/^"\(.*\)"$/"\1"/')
+        wait "$notification_killpid"
 
-	update_list=()
-
-	for i in "${all_updates_show[@]}"
-	do
-
-		if [[ "$i" == *" [FLATPAK]\"" ]] #if Flatpak application
-		then
-
-			name="${i::-11}\""
-
-			name="${name#\"}"
-
-			name="${name%\"}"
-
-			icon="$(grep -A 1 -B 3 "<name>$name</name>" /var/lib/flatpak/appstream/flathub/$(uname -m)/active/appstream.xml | grep '<id>' | awk -F'[<>]' '{print $3}')"
-
-			icon="${icon%% *}"
-
-			icon=$(echo "$icon" | head -n1)
-
-			if [[ "$icon" == *".desktop" ]]
-			then
-
-				icon="${icon::-8}"
-
-			fi
-
-			icon="$appstream_icons_dir/$icon.png"
-
-			if [[ ! -f "$icon" ]]
-			then
-
-				icon="/usr/share/shock-os-update-manager/flatpak.svg"
-
-			fi
-			
-			update_list+=("\"$icon\"" "\"$name\"")
-
-		else #if APT package
-
-            name="${i%%/*}"
-
-            name="${name#\"}"
-
-			icon="$(find /var/lib/app-info/icons/*/*/"$name"_* | head -1)"
-
-			if [[ ! -f "$icon" ]]
-			then
-
-				icon="/usr/share/shock-os-update-manager/apt.svg"
-
-			fi
-
-            full_name="$(grep -A 10000 "<pkgname>$name</pkgname>" /var/lib/app-info/xml/*.xml | grep '<name>' | head -n1 | awk -F'[<>]' '{print $3}')"
-
-            if [[ -n "$full_name" ]]
-            then
-
-                name="$full_name"
-
-            fi
-
-			update_list+=("\"$icon\"" "\"$name\"")
-
-		fi
-
-	done
-
-	echo "UPDATE LIST: ${update_list[@]}" #DEBUG
-
-	if ((${#update_list[@]}>rows_per_page))
-	then
-
-	    if ((page>0))
-	    then
-
-	        page_buttons='--button=Previous!gtk-go-forward-rtl:40 --button=Jump!gtk-jump-to-ltr:50 --button=Next!gtk-go-forward-ltr:60'
-
-	    else
-
-	        page_buttons='--button=Jump!gtk-jump-to-ltr:50 --button=Next!gtk-go-forward-ltr:60'
-
-	    fi
-
-	elif ((page>0))
-	then
-
-	    page_buttons='--button=Previous!gtk-go-forward-rtl:40 --button=Jump!gtk-jump-to-ltr:50' 
-
-	else
-
-	    page_buttons=""
-
-	fi
-
-	yadlist="yad --window-icon=system-software-update --title=\"Update Manager\" --width=800 --height=500 --text=\"Updates are available for the following apps/packages:\" --list --dclick-action=shock-os-update-manager-view-package --no-click --column=\"Icon\":IMG --column=\"Name\" $page_buttons --button=\"Install Updates\"\!system-software-update:1 ${update_list[@]}"
-
-	end_loading
-
-	eval "$yadlist"
-
-	ex=$?
-
-	if [[ "$ex" == "40" ]] #previous
-	then
-
-		page=$((page-1))
-
-	elif [[ "$ex" == "60" ]] #next
-	then
-
-		page=$((page+1))
-
-	elif [[ "$ex" == "50" ]] #jump
-	then
-
-		jump_page=$(yad --window-icon=system-software-update --title="Update Manager" --form --field="Jump to Page:":NUM "$((page+1))\!1..$(($(expr ${#search_results_prep_full[@]} / $rows_per_page)+1))" --button=Jump!gtk-jump-to-ltr)
-
-		ex=$?
-
-		jump_page=$(echo "$jump_page" | awk -F'|' '{print $1}')
-
-        if [[ "$ex" == "0" ]]
+        if [[ -f ~/.cache/shockware-center-launched-update-manager ]]
         then
 
-            page="$((jump_page-1))"
+            exit
 
         fi
 
-	elif [[ "$ex" == "1" ]] #install updates
-	then
+    fi
 
-		install_updates | zenity --window-icon=system-software-update --title="Update Manager" --text="Installing updates..." --progress --pulsate --auto-close --no-cancel
+    page=0
 
-		if [[ "$updates_cancelled" == "TRUE" ]] || ((${#all_updates[@]}>0)) #if there are STILL updates available (updates likely failed or were interrupted)
-		then
+    while true
+    do
 
-			yad --window-icon=emblem-important --image=emblem-important --title="Update Manager" --text="Failed to install the updates. Please double check your internet connection and try again later." --button="Dismiss" --width=400
+	    start_loading
 
-		else
+	    all_updates_show=("${all_updates[@]:$((rows_per_page*page))}")
 
-			yad --window-icon=emblem-default --image=emblem-default --title="Update Manger" --text="Your system is up to date." --button="Dismiss" --width=300
+	    all_updates_show=("${all_updates_show[@]::$((rows_per_page))}")
 
-		fi
+	    mapfile -t all_updates < <(printf '%s\n' "${all_updates[@]}" | sed 's/^"\(.*\)"$/"\1"/')
 
-		exit
+	    update_list=()
 
-	else
+	    for i in "${all_updates_show[@]}"
+	    do
 
-		exit
+		    if [[ "$i" == *" [FLATPAK]\"" ]] #if Flatpak application
+		    then
 
-	fi
+			    name="${i::-11}\""
+
+			    name="${name#\"}"
+
+			    name="${name%\"}"
+
+			    icon="$(grep -A 1 -B 3 "<name>$name</name>" /var/lib/flatpak/appstream/flathub/$(uname -m)/active/appstream.xml | grep '<id>' | awk -F'[<>]' '{print $3}')"
+
+			    icon="${icon%% *}"
+
+			    icon=$(echo "$icon" | head -n1)
+
+			    if [[ "$icon" == *".desktop" ]]
+			    then
+
+				    icon="${icon::-8}"
+
+			    fi
+
+			    icon="$appstream_icons_dir/$icon.png"
+
+			    if [[ ! -f "$icon" ]]
+			    then
+
+				    icon="/usr/share/shock-os-update-manager/flatpak.svg"
+
+			    fi
+			    
+			    update_list+=("\"$icon\"" "\"$name\"")
+
+		    else #if APT package
+
+                name="${i%%/*}"
+
+                name="${name#\"}"
+
+			    icon="$(find /var/lib/app-info/icons/*/*/"$name"_* | head -1)"
+
+			    if [[ ! -f "$icon" ]]
+			    then
+
+				    icon="/usr/share/shock-os-update-manager/apt.svg"
+
+			    fi
+
+                full_name="$(grep -A 10000 "<pkgname>$name</pkgname>" /var/lib/app-info/xml/*.xml | grep '<name>' | head -n1 | awk -F'[<>]' '{print $3}')"
+
+                if [[ -n "$full_name" ]]
+                then
+
+                    name="$full_name"
+
+                fi
+
+			    update_list+=("\"$icon\"" "\"$name\"")
+
+		    fi
+
+	    done
+
+	    echo "UPDATE LIST: ${update_list[@]}" #DEBUG
+
+	    if ((${#update_list[@]}>rows_per_page))
+	    then
+
+	        if ((page>0))
+	        then
+
+	            page_buttons='--button=Previous!gtk-go-forward-rtl:40 --button=Jump!gtk-jump-to-ltr:50 --button=Next!gtk-go-forward-ltr:60'
+
+	        else
+
+	            page_buttons='--button=Jump!gtk-jump-to-ltr:50 --button=Next!gtk-go-forward-ltr:60'
+
+	        fi
+
+	    elif ((page>0))
+	    then
+
+	        page_buttons='--button=Previous!gtk-go-forward-rtl:40 --button=Jump!gtk-jump-to-ltr:50' 
+
+	    else
+
+	        page_buttons=""
+
+	    fi
+
+	    yadlist="yad --window-icon=system-software-update --title=\"Update Manager\" --width=800 --height=500 --text=\"Updates are available for the following apps/packages:\" --list --dclick-action=shock-os-update-manager-view-package --no-click --column=\"Icon\":IMG --column=\"Name\" $page_buttons --button=\"Settings\"\!gnome-settings:1 --button=\"Install Updates\"\!system-software-update:2 ${update_list[@]}"
+
+	    end_loading
+
+	    eval "$yadlist"
+
+	    ex=$?
+
+	    if [[ "$ex" == "40" ]] #previous
+	    then
+
+		    page=$((page-1))
+
+	    elif [[ "$ex" == "60" ]] #next
+	    then
+
+		    page=$((page+1))
+
+	    elif [[ "$ex" == "50" ]] #jump
+	    then
+
+		    jump_page=$(yad --window-icon=system-software-update --title="Update Manager" --form --field="Jump to Page:":NUM "$((page+1))\!1..$(($(expr ${#search_results_prep_full[@]} / $rows_per_page)+1))" --button=Jump!gtk-jump-to-ltr)
+
+		    ex=$?
+
+		    jump_page=$(echo "$jump_page" | awk -F'|' '{print $1}')
+
+            if [[ "$ex" == "0" ]]
+            then
+
+                page="$((jump_page-1))"
+
+            fi
+
+        elif [[ "$ex" == "1" ]] #settings
+        then
+
+            if [[ -f /etc/sudoers.d/shock_automatic_updates ]] #if automatic updates are enabled
+            then
+
+                automatic_updates="TRUE"
+
+            else #if disabled
+
+                automatic_updates="FALSE"
+
+            fi
+
+            if [[ ! -f /usr/share/shock-os-update-manger/disable-release-upgrader-indicator ]] #if notification of new versions of Shock OS is enabled
+            then
+
+                notify_of_new_versions_of_shock_os="TRUE"
+
+            else #if disabled
+
+                notify_of_new_versions_of_shock_os="FALSE"
+
+            fi
+
+            settings="$(yad --window-icon=system-software-update --title="Settings" --form --field="If enabled, automatic updates will as root on a daily basis. You cannot log out, shutdown, or restart the system while automatic updates are being applied.":LBL "" --field="Automatic updates":CHK "$automatic_updates" --field="If enabled, you will be notified when an upgrade to a new version of Shock OS is available.":LBL "" --field="Notify me of new versions of Shock OS":CHK "$notify_of_new_versions_of_shock_os" --button="Apply"\!gtk-ok)"
+
+            automatic_updates=$(echo $settings | awk 'BEGIN {FS="|" } { print $2 }')
+
+            notify_of_new_versions_of_shock_os=$(echo $settings | awk 'BEGIN {FS="|" } { print $4 }')
+
+            if [[ "$automatic_updates" == "TRUE" ]] && [[ ! -f /etc/sudoers.d/shock_automatic_updates ]] #enable automatic updates
+            then
+
+                echo 'ALL ALL=NOPASSWD:/usr/bin/shock-auto-updates' | pkexec tee /etc/sudoers.d/shock_automatic_updates
+
+            elif [[ "$automatic_updates" == "FALSE" ]] && [[ -f /etc/sudoers.d/shock_automatic_updates ]] #disable automatic updates
+            then
+
+                pkexec rm /etc/sudoers.d/shock_automatic_updates
+
+            fi
+
+            if [[ "$notify_of_new_versions_of_shock_os" == "TRUE" ]] && [[ -f /usr/share/shock-os-update-manger/disable-release-upgrader-indicator ]] #enable notification of new versions of Shock OS
+            then
+
+                pkexec rm /usr/share/shock-os-update-manger/disable-release-upgrader-indicator
+
+            elif [[ "$notify_of_new_versions_of_shock_os" == "FALSE" ]] && [[ ! -f /usr/share/shock-os-update-manger/disable-release-upgrader-indicator ]] #disable notification of new versions of Shock OS
+            then
+
+                pkexec touch /usr/share/shock-os-update-manger/disable-release-upgrader-indicator
+
+            fi
+
+	    elif [[ "$ex" == "2" ]] #install updates
+	    then
+
+		    install_updates | zenity --window-icon=system-software-update --title="Update Manager" --text="Installing updates..." --progress --pulsate --auto-close --no-cancel
+
+            all_updates=($(printf "%s\n" "${all_updates[@]}" | sort))
+
+		    if [[ "$updates_cancelled" == "TRUE" ]] || ((${#all_updates[@]}>0)) #if there are STILL updates available (updates likely failed or were interrupted)
+		    then
+
+			    yad --window-icon=emblem-important --image=emblem-important --title="Update Manager" --text="Failed to install the updates. Please double check your internet connection and try again later." --button="Dismiss" --width=400
+
+		    else
+
+			    yad --window-icon=emblem-default --image=emblem-default --title="Update Manger" --text="Your system is up to date." --button="Dismiss" --width=300
+
+		    fi
+
+		    exit
+
+        elif [[ "$1" == "gui" ]] #if launched from the Shockware Center
+        then
+
+            exit
+
+        else
+
+            break
+
+	    fi
+
+    done
 
 done
 
