Minor changes and bug fixes. The error messages in the Release Upgrader and the Shock OS Imager have been updated and now work much better, but the Zenity windows are acting wierd, so still gotta figure that out. 	modified:   shockos-8.0-all/usr/bin/shock-os-imager 	modified:   shockos-8.0-all/usr/bin/shock-os-update-manager 	modified:   shockos-8.0-all/usr/bin/shock-release-upgrader 	new file:   templates/yad progress with kill

diff --git a/shockos-8.0-all/usr/bin/shock-os-imager b/shockos-8.0-all/usr/bin/shock-os-imager
--- a/shockos-8.0-all/usr/bin/shock-os-imager
+++ b/shockos-8.0-all/usr/bin/shock-os-imager
@@ -297,7 +297,15 @@ then
 
 		echo "$url" #DEBUG
 
-		(wget "$url" -P /usr/share/shock-os-imager/cached-images 2>&1 || (zenity --error --text="Failed to download $image_to_flash_display. The program will now exit." --ok-label="Exit" ; kill $$)) | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --no-cancel --auto-close --auto-kill
+		{
+
+        wget "$url" -P /usr/share/shock-os-imager/cached-images 2>&1 || {
+
+            zenity --error --text="Failed to download $image_to_flash_display. The program will now exit." --ok-label="Exit" ; kill $$
+
+            }
+
+        } | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --no-cancel --auto-close --auto-kill
 
 		mv /usr/share/shock-os-imager/cached-images/download /usr/share/shock-os-imager/cached-images/$filename
 
@@ -321,7 +329,48 @@ then
 
 	done | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Unmounting file systems on $target_device..." --progress --pulsate --no-cancel --auto-close
 
-	(sudo unxz -c /usr/share/shock-os-imager/cached-images/"$filename" || (zenity --error --text="An error occurred when extracting the image. The program will now exit." ; kill $$)) | (sudo dd of=$target_drive bs=4M status=progress || (zenity --error --text="An error occurred when writing the image. The program will now exit." ; kill $$)) | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --auto-close --auto-kill --no-cancel
+#THE WRITE SEGMENT BEGINS
+
+    # Launch the command in the background and capture its PID
+    sudo unxz -c /usr/share/shock-os-imager/cached-images/"$filename" | sudo dd of=$target_drive bs=4M status=progress > /dev/null 2>&1 & command_pid=$!
+
+    # Show the progress window using yad
+    {
+
+    zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --width=300 --height=100 --cancel-label="Cancel"
+
+    ex=$?
+
+    if [[ "$ex" != "0" ]]
+    then
+
+        kill -9 "$command_pid"
+        
+    fi
+
+    } &
+
+    # Capture the yad progress window's PID
+    yad_pid=$!
+
+    # Wait for the command to finish
+    wait "$command_pid"
+
+    # Get the command's exit code
+    ex=$?
+
+    # Close the yad progress window (if it's still open)
+    kill "$yad_pid"
+
+    # Check if the command exited with a non-zero code and show an error message if needed
+    if [[ "$ex" != "0" ]]
+    then
+
+        zenity --error --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="An error occurred when writing the image. The program will now exit." --ok-label="Exit" ; kill $$
+
+    fi
+
+#THE WRITE SEGMENT ENDS
 
 	zenity --notification --title="Flashing Complete" --text="$image_to_flash_display has successfully been flashed to $target_drive_display_name."
 
diff --git a/shockos-8.0-all/usr/bin/shock-release-upgrader b/shockos-8.0-all/usr/bin/shock-release-upgrader
--- a/shockos-8.0-all/usr/bin/shock-release-upgrader
+++ b/shockos-8.0-all/usr/bin/shock-release-upgrader
@@ -64,7 +64,7 @@ then
 
     fi
 
-    zenity --info --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Prepare to Upgrade" --text="Before upgrading, please make sure of the following:
+    zenity --question --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Prepare to Upgrade" --text="Before upgrading, please make sure of the following:
 
 1. The system is connected to a constant power supply.
 
@@ -74,7 +74,7 @@ then
 
 NOTE: The logout and power options in the start menu will be temporarily disabled while upgrading because powering off the machine during the upgrade process is highly discouraged and may render your system unusable.
 
-Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Continue"
+Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Upgrade to Shock OS $upgrto_version_display_name $upgrto_version_codename" --cancel-label="Cancel"
 
     ex=$?
 
@@ -89,11 +89,60 @@ Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Co
 
     rm -rf /usr/share/shock-release-upgrader/upgrades/*
 
-    (wget https://sourceforge.net/projects/shock-os-download-mirror/files/Upgrade-Packages/shock-release-upgrader/"$upgrto_version.zip"/download -P /usr/share/shock-release-upgrader/upgrades 2>&1 || (zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Download Failed" --text="Failed to download the upgrade pack." --ok-label="Exit" ; kill $$)) | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-release-upgrader/icon.svg --progress --title="Downloading the Upgrade Pack" --width=310 --text="Downloading the Shock OS $upgrto_version_display_name $upgrto_version_codename upgrade pack. This may take a while..." --no-cancel --auto-close --auto-kill
+    {
+
+    wget https://sourceforge.net/projects/shock-os-download-mirror/files/Upgrade-Packages/shock-release-upgrader/"$upgrto_version.zip"/download -P /usr/share/shock-release-upgrader/upgrades 2>&1 || {
+
+        zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Download Failed" --text="Failed to download the upgrade pack. The upgrade has been cancelled." --ok-label="Exit" ; exit 1
+
+        }
+
+    } | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-release-upgrader/icon.svg --progress --title="Downloading the Upgrade Pack" --width=310 --text="Downloading the Shock OS $upgrto_version_display_name $upgrto_version_codename upgrade pack. This may take a while..." --auto-close --auto-kill --cancel-label="Cancel Upgrade"
 
     cd /usr/share/shock-release-upgrader/upgrades
 
-    (unp -f download 2>&1 || (zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Unpack" --text="Failed to unpack the upgrade pack." --ok-label="Exit" ; kill $$)) | yad --center --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Unpacking the Upgrade Pack..." --text="Unpacking the Shock OS $upgrto_version_display_name $upgrto_version_codename upgrade pack. This may take a while..." -no-buttons --no-escape --undecorated --auto-close --auto-kill --progress --pulsate --progress-text="" --no-buttons
+#THE UNP SEGMENT BEGINS
+
+    # Launch the command in the background and capture its PID
+    unp -f download > /dev/null 2>&1 & command_pid=$!
+
+    # Show the progress window using yad
+    {
+
+    zenity --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Unpacking the Upgrade Pack" --text="Unpacking the Shock OS $upgrto_version_display_name $upgrto_version_codename upgrade pack. This may take a while..." --progress --pulsate --width=300 --height=100 --cancel-label="Cancel Upgrade"
+
+    ex=$?
+
+    if [[ "$ex" != "0" ]]
+    then
+
+        kill -9 "$command_pid"
+        
+    fi
+
+    } &
+
+    # Capture the yad progress window's PID
+    yad_pid=$!
+
+    # Wait for the command to finish
+    wait "$command_pid"
+
+    # Get the command's exit code
+    ex=$?
+
+    # Close the yad progress window (if it's still open)
+    kill "$yad_pid"
+
+    # Check if the command exited with a non-zero code and show an error message if needed
+    if [[ "$ex" != "0" ]]
+    then
+
+        zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Unpack" --text="Failed to unpack the upgrade pack. The upgrade has been cancelled." --ok-label="Exit" ; exit 1
+
+    fi
+
+#THE UNP SEGMENT ENDS
 
     rm download
 
@@ -101,7 +150,48 @@ Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Co
 
     chmod --recursive 755 $upgrto_version/DEBIAN
 
-    (dpkg-deb --build -Zxz "$upgrto_version" 2>&1 || (zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Upgrade" --text="Failed to package the upgrade." --ok-label="Exit" ; kill $$)) | yad --center --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Preparing to Upgrade..." --text="Preparing to upgrade to Shock OS $upgrto_version_display_name $upgrto_version_codename. Please sit tight, this may take a while..." -no-buttons --no-escape --undecorated --auto-close --auto-kill --progress --pulsate --progress-text="" --no-buttons
+#THE DPKG-DEB SEGMENT BEGINS
+
+    # Launch the command in the background and capture its PID
+    dpkg-deb --build -Zxz "$upgrto_version" > /dev/null 2>&1 & command_pid=$!
+
+    # Show the progress window using yad
+    {
+
+    zenity --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Preparing to Upgrade..." --text="Preparing to upgrade to Shock OS $upgrto_version_display_name $upgrto_version_codename. Please sit tight, this may take a while..." --progress --pulsate --width=300 --height=100 --cancel-label="Cancel Upgrade"
+
+    ex=$?
+
+    if [[ "$ex" != "0" ]]
+    then
+
+        kill -9 "$command_pid"
+        
+    fi
+
+    } &
+
+    # Capture the yad progress window's PID
+    yad_pid=$!
+
+    # Wait for the command to finish
+    wait "$command_pid"
+
+    # Get the command's exit code
+    ex=$?
+
+    # Close the yad progress window (if it's still open)
+    kill "$yad_pid"
+
+    # Check if the command exited with a non-zero code and show an error message if needed
+    if [[ "$ex" != "0" ]]
+    then
+
+        zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Upgrade" --text="Failed to package the upgrade. The upgrade has been cancelled." --ok-label="Exit" ; exit 1
+
+    fi
+
+#THE DPKG-DEB SEGMENT ENDS
 
     sudo wget https://raw.githubusercontent.com/Shock-OS/Shock-OS/upgrades/$upgrto_version-preupgr-script -P /usr/share/shock-release-upgrader/upgrades
 
@@ -114,7 +204,48 @@ Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Co
 
     fi
 
-    (sudo env DEBIAN_FRONTEND=gnome apt install -y ./"$upgrto_version.deb" 2>&1 || (zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Install Update" --text="Failed to install the upgrade pack." --ok-label="Exit" ; kill $$)) | yad --center --progress --pulsate --auto-close --auto-kill --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Upgrading to Shock OS $upgrto_version_display_name $upgrto_version_codename" --text="Upgrading to Shock OS $upgrto_version_display_name $upgrto_version_codename. Please sit tight, this may take a while..." --no-buttons --no-escape --undecorated --progress-text=""
+#THE APT INSTALL SEGMENT BEGINS
+
+    # Launch the command in the background and capture its PID
+    sudo env DEBIAN_FRONTEND=gnome apt install -y ./"$upgrto_version.deb" > /dev/null 2>&1 & command_pid=$!
+
+    # Show the progress window using yad
+    {
+
+    zenity --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Upgrading to Shock OS $upgrto_version_display_name $upgrto_version_codename" --text="Upgrading to Shock OS $upgrto_version_display_name $upgrto_version_codename. Please sit tight, this may take a while..." --progress --pulsate --width=300 --height=100 --cancel-label="Cancel Upgrade"
+
+    ex=$?
+
+    if [[ "$ex" != "0" ]]
+    then
+
+        kill -9 "$command_pid"
+        
+    fi
+
+    } &
+
+    # Capture the yad progress window's PID
+    yad_pid=$!
+
+    # Wait for the command to finish
+    wait "$command_pid"
+
+    # Get the command's exit code
+    ex=$?
+
+    # Close the yad progress window (if it's still open)
+    kill "$yad_pid"
+
+    # Check if the command exited with a non-zero code and show an error message if needed
+    if [[ "$ex" != "0" ]]
+    then
+
+        zenity --error --window-icon=/usr/share/shock/shock-release-upgrader.svg --title="Failed to Upgrade" --text="Failed to install the upgrade pack. The upgrade has been cancelled." --ok-label="Exit" ; exit 1
+
+    fi
+
+#THE APT INSTALL SEGMENT ENDS
 
     sudo wget https://raw.githubusercontent.com/Shock-OS/Shock-OS/upgrades/$upgrto_version-postupgr-script -P /usr/share/shock-release-upgrader/upgrades
 
