Programs that need them now have error messages. Upon a an error, the message will display, and the command will then exit if the error is fatal. This improves the stability of these programs. 	modified:   shockos-8.0-all/usr/bin/shock-initial-setup 	modified:   shockos-8.0-all/usr/bin/shock-os-imager 	modified:   shockos-8.0-all/usr/bin/shock-os-update-manager 	modified:   shockos-8.0-all/usr/bin/shock-package-installer 	modified:   shockos-8.0-all/usr/bin/shock-parental-controls 	modified:   shockos-8.0-all/usr/bin/shock-release-upgrader 	modified:   shockos-8.0-all/usr/bin/shock-slideshow-wallpaper 	modified:   shockos-8.0-all/usr/bin/shock-users

diff --git a/shockos-8.0-all/usr/bin/shock-os-imager b/shockos-8.0-all/usr/bin/shock-os-imager
--- a/shockos-8.0-all/usr/bin/shock-os-imager
+++ b/shockos-8.0-all/usr/bin/shock-os-imager
@@ -276,7 +276,7 @@ then
 				if [[ ! -f /usr/share/shock-os-imager/images ]]
 				then
 
-					yad --window-icon=/usr/share/shock-os-imager/icon.svg --window-icon=emblem-important --text="You are not connected to the internet, and an image for the Shock OS version you selected is not cached. Please either connect to the internet and hit 'Retry', or cancel." --button="Retry"\!edit-undo --button="Cancel"\!gtk-cancel
+					yad --window-icon=/usr/share/shock-os-imager/icon.svg --image=emblem-important --width=400 --title="No Internet" --text="You are not connected to the internet, and an image for the Shock OS version you selected is not cached. Please either connect to the internet and hit 'Retry', or cancel." --button="Retry"\!edit-undo --button="Cancel"\!gtk-cancel
 
 					ex=$?
 
@@ -297,27 +297,18 @@ then
 
 		echo "$url" #DEBUG
 
-		wget "$url" -P /usr/share/shock-os-imager/cached-images 2>&1 | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --no-cancel --auto-close
+		(wget "$url" -P /usr/share/shock-os-imager/cached-images 2>&1 || (zenity --error --text="Failed to download $image_to_flash_display. The program will now exit." --ok-label="Exit" ; kill $$)) | sed -u 's/.* \([0-9]\+%\)\ \+\([0-9.]\+.\) \(.*\)/\1\n# Downloading at \2\/s, ETA \3/' | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --progress --title="Downloading $image_to_flash_display" --width=310 --text="Downloading $image_to_flash_display. This may take a while..." --no-cancel --auto-close --auto-kill
 
 		mv /usr/share/shock-os-imager/cached-images/download /usr/share/shock-os-imager/cached-images/$filename
-
-		if [[ ! -f /usr/share/shock-os-imager/cached-images/$filename ]] #if download failed
-		then
-
-			yad --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="The download failed or was interrupted. The operation has been aborted." --button="Dismiss"\!gtk-quit
-
-			exit
-
-		fi
 
 	fi
 
     if [[ -z "$(lsblk -o PATH | grep -w $target_drive)" ]] #if error reading the device (perhaps it was unplugged)
     then
 
-        zenity --window-icon=/usr/share/shock-os-imager/icon.svg --error --title="Shock OS Imager" --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Dismiss" --width=300
+        zenity --error --text="An error occured while preparing '$target_drive_display_name' for flashing. Perhaps it was unplugged." --ok-label="Exit"
 
-        exit
+        exit 1
 
     fi
 
@@ -330,7 +321,7 @@ then
 
 	done | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Unmounting file systems on $target_device..." --progress --pulsate --no-cancel --auto-close
 
-	sudo unxz -c /usr/share/shock-os-imager/cached-images/"$filename" | sudo dd of=$target_drive bs=4M status=progress | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --auto-close --no-cancel
+	(sudo unxz -c /usr/share/shock-os-imager/cached-images/"$filename" || (zenity --error --text="An error occurred when extracting the image. The program will now exit." ; kill $$)) | (sudo dd of=$target_drive bs=4M status=progress || (zenity --error --text="An error occurred when writing the image. The program will now exit." ; kill $$)) | zenity --window-icon=/usr/share/shock-os-imager/icon.svg --title="Shock OS Imager" --text="Writing $image_to_flash_display to $target_drive_display_name. This will take about 30 minutes..." --progress --pulsate --auto-close --auto-kill --no-cancel
 
 	zenity --notification --title="Flashing Complete" --text="$image_to_flash_display has successfully been flashed to $target_drive_display_name."
 
diff --git a/shockos-8.0-all/usr/bin/shock-package-installer b/shockos-8.0-all/usr/bin/shock-package-installer
--- a/shockos-8.0-all/usr/bin/shock-package-installer
+++ b/shockos-8.0-all/usr/bin/shock-package-installer
@@ -12,16 +12,16 @@ fi
 if [[ -d "$file" ]] #if a directory was selected instead of a file
 then
 
-    yad --window-icon=package --image=emblem-important --width=400 --title="Package Installer" --text="$(basename "$file") is a folder, not a .deb package." --button="Dismiss"\!gtk-quit
+    zenity --error --text="$(basename "$file") is a folder, not a .deb package." --ok-label="Exit"
 
-    exit
+    exit 1
 
 elif [[ "$file" != *".deb" ]] #if not a .deb package
 then
 
-    yad --window-icon=package --image=emblem-important --width=400 --title="Package Installer" --text="$(basename "$file") is not a .deb package." --button="Dismiss"\!gtk-quit
+    zenity --error --text="$(basename "$file") is not a .deb package." --ok-label="Exit"
 
-    exit
+    exit 1
 
 fi
 
@@ -34,16 +34,16 @@ arch="$(dpkg -I "$file" | grep Architecture: | awk '{print $2}')"
 if ! [[ "$arch" == "all" || "$arch" == *"arm"* ]] #if not an ARM package
 then
 
-    yad --window-icon=package --image=emblem-important --width=400 --title="Package Installer" --text="$(basename "$file") is in an architecture that is incompatible with your system. Please use an ARM (armhf or arm64) version of the package if possible. i386 and amd64 packages will NOT work." --button="Dismiss"\!gtk-quit
+    zenity --error --text="$(basename "$file") is in an architecture that is incompatible with your system. Please use an ARM (armhf or arm64) version of the package if possible. i386 and amd64 packages will NOT work." --ok-label="Exit"
 
-    exit
+    exit 1
 
 elif [[ "$(getconf LONG_BIT)" == "32" ]] && ! [[ "$arch" == "all" || "$arch" == *"armhf"* ]] #if it is an ARM package, check for compatibility on 32-bit systems (32-bit)
 then
 
-    yad --window-icon=package --image=emblem-important --width=400 --title="Package Installer" --text="$(basename "$file") is a 64-bit package (arm64), but your system is only 32-bit (armhf). Please use a 32-bit (armhf) version of the package if possible." --button="Dismiss"\!gtk-quit
+    zenity --error --text="$(basename "$file") is a 64-bit package (arm64), but your system is only 32-bit (armhf). Please use a 32-bit (armhf) version of the package if possible." --ok-label="Exit"
 
-    exit
+    exit 1
 
 fi
 
@@ -175,7 +175,9 @@ then
 
     else #if package was not installed successfully
 
-        yad --window-icon=package --image=emblem-important --title="Package Installer" --text="Failed to install $package_display_name. Please double check your internet connection and try again later." --button="Dismiss"\!gtk-quit
+        zenity --error --text="Failed to install $package_display_name. Please double check your internet connection and try again later." --ok-label="Exit"
+
+        exit 1
 
     fi
 
@@ -189,7 +191,9 @@ then
 
     else #if package was not installed successfully
 
-        yad --window-icon=package --image=emblem-important --title="Package Installer" --text="Failed to remove $package_display_name." --button="Dismiss"\!gtk-quit
+        zenity --error --text="Failed to remove $package_display_name." --ok-label="Exit"
+
+        exit 1
 
     fi
 
diff --git a/shockos-8.0-all/usr/bin/shock-users b/shockos-8.0-all/usr/bin/shock-users
--- a/shockos-8.0-all/usr/bin/shock-users
+++ b/shockos-8.0-all/usr/bin/shock-users
@@ -180,7 +180,7 @@ then
 
         x=$(echo "$x" | tr -cd '[:alnum:]._-') #this command removes all numbers
 
-        adduser --disabled-password --gecos "$full_name" $x #the user has been created
+        adduser --disabled-password --gecos "$full_name" $x || (zenity --error --text="Failed to create a new user. The program will now exit." --ok-label="Exit" ; kill $$) #the user has been created
 
         echo "$x:$pa1" | chpasswd
 
@@ -191,13 +191,13 @@ then
         if [[ "$kidprofile" == "TRUE" ]]
         then
 
-            groupadd shock-child
+            groupadd shock-child || (zenity --error --text="Failed to create the 'shock-child' group. The program will now exit." --ok-label="Exit" ; kill $$)
 
-            usermod -a -G adm,dialout,cdrom,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio,shock-child $x #the user has been added to the required groups (excluding sudo)
+            usermod -a -G adm,dialout,cdrom,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio,shock-child $x || (zenity --error --text="Failed to add the user to the required groups. The program will now exit." --ok-label="Exit" ; kill $$) #the user has been added to the required groups (excluding sudo)
 
         else
 
-            usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio $x #the user has been added to the required groups
+            usermod -a -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio $x || (zenity --error --text="Failed to add the user to the required groups. The program will now exit." --ok-label="Exit" ; kill $$) #the user has been added to the required groups
 
         fi
 
@@ -282,7 +282,7 @@ then
 
     #child profile files removed
 
-    deluser --remove-home $user_to_remove
+    deluser --remove-home $user_to_remove || (zenity --error --text="Failed to remove $user_to_remove. The program will now exit." --ok-label="Exit" ; kill $$)
 
     yad --window-icon=system-users --title="User Successfully Removed" --text="Congratulations! The user '$user_to_remove_display_name' has successfully been removed." --button="Dismiss"\!gtk-quit
 
